from utility import DataMocking
def run():
    project = DataMocking()
    project.insert_fields()
    print("Done: fields")
    project.insert_users()
    print("Done: users")
    project.insert_product_type()
    print("Done: product_type")
    project.insert_products()
    print("Done: products")
    project.insert_portable_devices()
    print("Done: portable_devices")
    project.insert_records()
    print("Done: records")
    project.insert_plantings()
    print("Done: plantings")
    project.insert_harvest()
    print("Done: harvest")
    project.insert_portable_devices_communities()
    print("Done: portable_devices_communities")
    project.insert_planting_devices()
    print("Done: planting_devices")
    project.insert_harvest_devices()
    print("Done: harvest_devices")
    project.insert_weather_metrics()
    print("Done: weather_metrics")
    project.insert_cultivation()
    print("Done: cultivation")
    project.insert_cultivation_devices()
    print("Done: cultivation_devices")
    project.insert_devices_calendars()
    print("Done: devices_calendars")
run()