from utility import DataMocking
def run():
    project = DataMocking()
    project.insert_fields()
    project.insert_product_type()
    project.insert_products()
    project.insert_portable_devices()
    project.insert_records()
    project.insert_plantings()
    project.insert_harvest()
    project.insert_portable_devices_communities()
    project.insert_planting_devices()
    project.insert_harvest_devices()
    project.insert_weather_metrics()
    project.insert_cultivation()
    project.insert_cultivation_devices()
run()